version: '3.8'
services:
  database:
    image: postgres:16-alpine
    container_name: token-price-tracker-db
    volumes:
      - ./data:/data/db
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=token-price-tracker
